config/routes.rb
Rails.application.routes.draw do

  
  get 'users/index'

  root "dashboards#index"

  devise_for :users 
  resources :projects do 
    resources :todos,  only: [:index, :create, :update, :edit, :destroy]
    resources :assign_projects, only: [:index, :create, :destroy]
  end
  resources :users do
    get :autocomplete_user_email, :on => :collection
    get 'autocomplete_user_project/:project_id' => "users#autocomplete_user_project", :on => :collection, as: :autocomplete_user_project
  end

end

app/models/assign_project.rb
class AssignProject < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
	has_many :todos
	before_save :assign_status_to_newely_created_project

	def assign_status_to_newely_created_project
		self.status = CREATED if self.id.nil? and not self.status.present?
	end

	def get_project_admin

  	  AssignProject.where(project_id: self.project_id, status: CREATED).first.user
    end
end

app/controllers/assign_projects_controller.rb
class AssignProjectsController < ApplicationController
  before_action :set_assign_project, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  before_action :set_user, only: [:show, :create, :update]

  def index
    @assign_projects = @project.assign_projects.where(status: ASSIGNED)
  end

  def show
  end

  def new
    @assign_project = AssignProject.new
  end

  def edit
  end

  def create
    @assign_project = @project.assign_projects.new(status: ASSIGNED, user_id: @user.id)
    return render :new if not @assign_project.save
    redirect_to [@project, AssignProject], notice: 'Assign project was successfully created.'
       
  end

  def update
    return render :edit if not @assign_project.update(assign_project_params)
    redirect_to [@project, AssignProject], notice: 'Assign project was successfully updated.'
  end

  def destroy
    @assign_project.destroy
    redirect_to [@project, AssignProject], notice: 'Assign project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assign_project
      @assign_project = AssignProject.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
      if not @project
        redirect_to root_path, notice: 'Unauthorized access'  
      end
    end

    def set_user
      @user = User.find_by_email(params[:user][:user_email])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assign_project_params
      params.require(:assign_project).permit(:users, :projects)
    end
end

app/helpers/assign_projects_helper.rb
module AssignProjectsHelper
end

app/views/assign_projects/_form.html.haml
= form_for(@assign_project) do |f|
  - if @assign_project.errors.any?
    #error_explanation
      %h2
        = pluralize(@assign_project.errors.count, "error")
        prohibited this assign_project from being saved:
      %ul
        - @assign_project.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :users
    %br/
    = f.text_field :users
  .field
    = f.label :projects
    %br/
    = f.text_field :projects
  .actions
    = f.submit

app/views/assign_projects/edit.html.haml
%h1 Editing Assign Project
= render 'form'
= link_to 'Show', @assign_project
|
= link_to 'Back', assign_projects_path

app/views/assign_projects/index.html.haml
.col-md-4
.col-md-4
  %h1 Assign Project
.col-md-12
  .col-md-4
  .col-md-4
    = form_for :user do |f|
      = f.hidden_field :status, value: ASSIGNED
      .form-group
        %label{:for => "usr"} User Name:
        = f.autocomplete_field :user_email, autocomplete_user_email_users_path, class: "form-control"
      
      .form-group
        = f.submit "Submit", class: "btn btn-default"
  .col-md-4
%br/


.container
  %h2 List of #{@project.name}
  %p 
  %table.table.table-hover
    %thead
      %tr
        %th User/projects
        %th Assigned Users
        %th Projects
        %th Action
    %tbody
      - @assign_projects.each do |assign_project|
        %tr
          %td
            = assign_project.get_project_admin.email
            \/
            = assign_project.project.name
          %td= assign_project.user.email rescue nil
          %td= link_to 'Destroy', [@project, assign_project], method: :delete, data: { confirm: 'Are you sure?' }
          %td= link_to 'Todo', [@project, Todo]

app/views/assign_projects/new.html.haml
%h1 New Assign Project
= render 'form'
= link_to 'Back', assign_projects_path

app/views/assign_projects/show.html.haml
%p#notice= notice
%p
  %strong Users:
  = @assign_project.users
%p
  %strong Projects:
  = @assign_project.projects
= link_to 'Edit', edit_assign_project_path(@assign_project)
|
= link_to 'Back', assign_projects_path