config/routes.rb
Rails.application.routes.draw do

  
  get 'users/index'

  root "dashboards#index"

  devise_for :users 
  resources :projects do 
    resources :todos,  only: [:index, :create, :update, :edit, :destroy]
    resources :assign_projects, only: [:index, :create, :destroy]
  end
  resources :users do
    get :autocomplete_user_email, :on => :collection
    get 'autocomplete_user_project/:project_id' => "users#autocomplete_user_project", :on => :collection, as: :autocomplete_user_project
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
	has_many :assign_projects
	has_many :users, through: :assign_projects
	has_many :todos, through: :assign_projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.create(project_params)
    return render :new  if @project.errors.present?
    redirect_to projects_path, notice: 'Project was successfully created.'
  end

  def update
    return render :edit if not @project.update(project_params)
    redirect_to @project, notice: 'Project was successfully updated.'
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
.col-md-12
  .col-md-4
  .col-md-4
    = form_for(@project) do |f|
      .form-group
        %label{:for => "usr"} User Name:
        = f.text_field :name, class: "form-control"
      .form-group
        %label{:for => "pwd"} Task:
        = f.text_area :description, class: "form-control"
      .form-group
        = f.submit "Submit", class: "btn btn-default"
  .col-md-4
%br/

app/views/projects/edit.html.haml
.col-md-4
.col-md-4
  %h1 Edit Project
= render 'form'

app/views/projects/index.html.haml
.container
  %h2 List Of Projects
  %p 
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Description
        %th{:colspan => "4"} Action
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.name
          %td= project.description
          %td= link_to 'Todo', [project, Todo]
          - if current_user.has_role? :admin
            %td= link_to 'Assign Project', [project, AssignProject]
            %td= link_to 'Edit', edit_project_path(project)
            %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

app/views/projects/new.html.haml
.col-md-4
.col-md-4
  %h1 New Project
= render 'form'

app/views/projects/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @project.name
%p
  %strong Description:
  = @project.description
= link_to 'Edit', edit_project_path(@project)
|
= link_to 'Back', projects_path