config/routes.rb
Rails.application.routes.draw do

  
  get 'users/index'

  root "dashboards#index"

  devise_for :users 
  resources :projects do 
    resources :todos,  only: [:index, :create, :update, :edit, :destroy]
    resources :assign_projects, only: [:index, :create, :destroy]
  end
  resources :users do
    get :autocomplete_user_email, :on => :collection
    get 'autocomplete_user_project/:project_id' => "users#autocomplete_user_project", :on => :collection, as: :autocomplete_user_project
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  include AASM
	serialize :description
	attr_accessor :user_email, :project_id

	validates :assign_project_id, :description, :status, presence: true
	belongs_to :assign_project
	belongs_to :project
	belongs_to :user
	after_initialize :assign_todo_to_project
	aasm :column => :status do  # defaults to aasm_state
	    state :new, :initial => true
	    state :in_progress
	    state :done
	    
	    event :in_progress do 
	      transitions :from => [:new], :to => :in_progress
	    end
	    event :done do
	      transitions :from => [:new, :in_progress], :to => :done
	    end
	end

    def perform_event(event)
    begin
    case event
      when  "in_progress"
        self.in_progress!
      when  "done"
        self.done! 
    else  
    end
    rescue Exception => e   
      self.errors.add(:status, e.message)
    end
  end



	def assign_todo_to_project
		self.status = "" if self.id.nil? and not self.status.present?
		user = User.find_by_email(self.user_email) if self.user_email
		self.assign_project_id = user.assign_projects.find_by_project_id(self.project_id).id rescue nil if user
	end

	def self.get_todos(status, project)

	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  def index
    @todos = @project.todos
    @todo = Todo.new
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    return render :new unless @todo.save
    redirect_to [@project, Todo], notice: 'Todo was successfully created.'
       
  end

  def update
    return render :edit unless @todo.update(todo_params)
    redirect_to [@project, Todo], notice: 'Todo was successfully updated.' 
  end

  def destroy
    @todo.destroy
    redirect_to [@project, Todo], notice: 'Todo was successfully destroyed.' 
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
      if not @project
        redirect_to root_path, notice: 'Unauthorized access'  
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit!
    end
end

app/views/todos/_form.html.haml
.col-md-12
  .col-md-4
  .col-md-4
    %h1 Create Todos
.col-md-12
  .col-md-4
  .col-md-4
    = form_for([@project, @todo]) do |f|
      = f.hidden_field :project_id, value: @project.id
      .form-group
        %label{:for => "usr"} User Name:
        = f.autocomplete_field :user_email, autocomplete_user_project_users_path(project_id: @project.id), :update_element => {id: '#some_element'}, class: "form-control"
      .form-group
        %label{:for => "pwd"} Task:
        = f.text_area :description, class: "form-control"
      .form-group
        = f.submit "Submit", class: "btn btn-default"
  .col-md-4
%br/

app/views/todos/edit.html.haml
%h1 Editing Todo
= render 'form'
= link_to 'Show', @todo
|
= link_to 'Back', todos_path

app/views/todos/index.html.haml
- if current_user.has_role? :admin
  = render partial: "form"

.col-md-12
  .container
    %h2 Todos of #{@project.name}
    %p 
    %table.table.table-hover
      %thead
        %tr
          %th Description
          %th assigned to user
          %th Status
          %th
          %th Action
      %tbody
        - @todos.each do |todo|
          %tr
            %td= todo.description
            %td= todo.assign_project.user.email
            %td= todo.status
            %td
              - todos_status = todo.aasm.events.map{|eve| [eve.name.to_s.titlecase, eve.name]}
              = form_for [@project, todo], remote: true, html: {method: :put, class: "form_proj_act_#{todo.id}"} do |f|
                = hidden_field_tag :authenticity_token, form_authenticity_token
                = select(:todo, :status, ["Change Status"]+todos_status,{prompt: "Change Status", selected: todo.status}, onchange: "$('.form_proj_act_'+#{todo.id}).submit();")
            / %td= link_to 'Show', [@project, todo]
            / %td= link_to 'Edit', edit_project_todo_path(@project, todo)
            %td= link_to 'Destroy', [@project, todo], method: :delete, data: { confirm: 'Are you sure?' } if current_user.has_role? :admin
        

app/views/todos/new.html.haml
= render 'form'

app/views/todos/show.html.haml
%p#notice= notice
%p
  %strong Description:
  = @todo.description
= link_to 'Edit', edit_todo_path(@todo)
|
= link_to 'Back', todos_path