config/routes.rb
Rails.application.routes.draw do

  
  get 'users/index'

  root "dashboards#index"

  devise_for :users 
  resources :projects do 
    resources :todos,  only: [:index, :create, :update, :edit, :destroy]
    resources :assign_projects, only: [:index, :create, :destroy]
  end
  resources :users do
    get :autocomplete_user_email, :on => :collection
    get 'autocomplete_user_project/:project_id' => "users#autocomplete_user_project", :on => :collection, as: :autocomplete_user_project
  end

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Portfolio
    #myNavbar.collapse.navbar-collapse
      - if current_user
        %ul.nav.navbar-nav
          %li.active
            = link_to "Home", root_path
          %li
            =link_to 'Projects', projects_path
          %li
            =link_to 'Create Project', new_project_path
          - if  @project.present? and not @project.id.nil?
            %li
              = link_to "Todos", [@project, Todo]
            %li
              = link_to "Assign Project", [@project, AssignProject]
        %ul.nav.navbar-nav.navbar-right
          %li
            %a.navbar-brand{:href => "#"}
              = current_user.email rescue nil
          %li
            =link_to destroy_user_session_path, :method => :delete do 
              %span.glyphicon.glyphicon-log-in
              Sign out
              

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Assignment
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =  javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  / .hold-transition.skin-blue.sidebar-mini
  %body
    = render partial: 'layouts/header'
    %p#notice= notice

    = yield